import { createHash } from "node:crypto";
import { streamText } from "ai";
import { BUILDER_SYSTEM_PROMPT, extractFiles } from "@/lib/prompt";
import { resolveGenerationFor } from "@/lib/providers/gateway";
import {
  createProject,
  deleteAppFile,
  getProject,
  listAppFiles,
  saveAppFile,
  setProjectTemplate,
} from "@/lib/store";
import {
  TEMPLATES,
  briefHash,
  templateProjectId,
  type TemplateDef,
} from "@/lib/templates";
import type { ProjectFile } from "@/lib/types";

/**
 * Template demo generation, shared by:
 *  - POST /api/templates   (on-demand from the gallery)
 *  - warmTemplateCache()   (background pass on server start, instrumentation)
 *
 * Demos live in fixed-id "library projects" (`tpl-<id>`) and are cached:
 * a demo is fresh only while its briefHash matches the current brief.
 */

/**
 * Extra instruction for template generation. The brief is the file plan:
 * a demo must emit every file its brief describes — a multi-page brief
 * (SaaS site, blog) gets every page as a real .html file, never a
 * single-page stub whose nav links 404. Size guidance is per-file so a
 * five-file demo isn't squeezed into one 300-line page.
 *
 * The "emit exactly the files" rule governs PAGES, never styling. Reading
 * it literally once made four of six demos ship bare unstyled markup:
 * no brief names a stylesheet, so "no more, no fewer" talked the model out
 * of the one file that carries the entire visual design. The suffix
 * therefore mandates the design system explicitly.
 */
const TEMPLATE_SUFFIX = `

This is a TEMPLATE DEMO. Emit every page the brief describes — when it names
index.html, pricing.html, about.html, …, each is its own file linked with
plain relative paths, and the shared navbar/footer are duplicated per page
(no build step). When it describes a shared data file (e.g. posts.js), emit
it and have the pages read it. NEVER link to a file you did not emit.

Ship a real stylesheet with every demo: one styles.css holding the design
system (custom properties in :root, a deliberate palette, a type scale with
clamp(), grid/flex layout), linked from EVERY page. Unstyled markup is a
failed demo — a page that renders as browser-default HTML does not show off
anything. Interactive behavior belongs in one app.js, also linked from every
page. Keep each file focused and polished (roughly 100–200 lines per page):
a striking above-the-fold visual and a clean section flow beat raw length.

IMPORTANT: never reference image files (img src, background url) — no local
assets and no external URLs. Draw all visuals with inline SVG or CSS shapes
and gradients only; the demo must look complete with just its own files.
Never inline a base64-encoded raster image (a data:image/png;base64 blob) —
it bloats the file past every useful limit; use inline SVG or CSS gradients.`;

/**
 * Reject a demo whose html is truncated or unstyled: no <body>, or no
 * stylesheet/inline <style> anywhere. Without this, a generation that gets
 * cut off mid-output (the model emitted a 5 KB base64 og:image and the
 * response ended before <body>) is cached and served as a "ready" demo that
 * renders as a blank page. Retrying beats shipping it.
 */
export function demoLooksComplete(files: ProjectFile[]): boolean {
  const html = files.filter((f) => f.path.endsWith(".html"));
  if (html.length === 0) return false;
  if (!html.some((f) => /<body[\s>]/i.test(f.content))) return false;
  const styled =
    files.some((f) => f.path.endsWith(".css") && f.content.trim().length > 0) ||
    html.some((f) => /<style[\s>]/i.test(f.content));
  return styled;
}

/**
 * Cache key component: hash of everything the demo generation depends on
 * besides the brief. When the system prompt (or the template suffix) changes,
 * every cached demo becomes stale and is regenerated by the next warm pass.
 */
export function systemPromptHash(): string {
  return createHash("sha256")
    .update(BUILDER_SYSTEM_PROMPT, "utf8")
    .update(TEMPLATE_SUFFIX, "utf8")
    .digest("hex")
    .slice(0, 16);
}

export interface TemplateStatus {
  id: string;
  name: string;
  tagline: string;
  gradient: string;
  ready: boolean;
  generating: boolean;
  stale: boolean;
  files: string[];
  generatedAt?: string;
}

/** In-process lock so a warm pass and gallery clicks never double-generate. */
const generating = new Set<string>();

function statusFor(t: TemplateDef): TemplateStatus {
  const projectId = templateProjectId(t.id);
  const project = getProject(projectId);
  const files = project ? listAppFiles(projectId) : [];
  const fresh =
    project?.template?.briefHash === briefHash(t.brief) &&
    project?.template?.promptHash === systemPromptHash() &&
    files.length > 0;
  return {
    id: t.id,
    name: t.name,
    tagline: t.tagline,
    gradient: t.gradient,
    ready: fresh,
    generating: generating.has(t.id),
    stale: Boolean(project) && !fresh,
    files: files.map((f) => f.path),
    generatedAt: project?.template?.generatedAt,
  };
}

export interface TemplateCacheStatus {
  templates: TemplateStatus[];
  configured: boolean;
  /** True while the startup warm pass is still working through templates. */
  warming: boolean;
  /** Template ids still pending in the startup warm pass. */
  warmingPending: string[];
}

/** Warm-pass state, readable by the API for gallery polling. */
let warmActive = false;
const warmPending = new Set<string>();

export async function getTemplateCacheStatus(): Promise<TemplateCacheStatus> {
  return {
    templates: TEMPLATES.map(statusFor),
    configured: await isProviderConfigured(),
    warming: warmActive,
    warmingPending: [...warmPending],
  };
}

export async function isProviderConfigured(): Promise<boolean> {
  try {
    await resolveGenerationFor();
    return true;
  } catch {
    return false;
  }
}

/**
 * Generate (or regenerate when stale) one template's demo app server-side
 * into its library project. Returns the fresh status, or null when nothing
 * was generated (already generating / no provider / generation failed).
 * Never throws — the background warm pass and the fire-and-forget API path
 * both just want success/failure.
 */
export async function generateTemplateDemo(
  template: TemplateDef,
): Promise<TemplateStatus | null> {
  try {
    return await generateTemplateDemoOrThrow(template);
  } catch (err) {
    console.error(
      `[templates] ${template.id}: generation failed —`,
      err instanceof Error ? err.message : err,
    );
    return null;
  }
}

/**
 * Generate one template's demo, throwing on failure with a message suitable
 * for the gallery's error banner (no provider, degenerate output, …).
 */
export async function generateTemplateDemoOrThrow(
  template: TemplateDef,
): Promise<TemplateStatus> {
  if (generating.has(template.id)) {
    throw new Error("Already generating");
  }
  let generation;
  try {
    generation = await resolveGenerationFor();
  } catch (err) {
    throw new Error(
      err instanceof Error
        ? err.message
        : "No AI provider configured — set one in Settings first.",
    );
  }

  generating.add(template.id);
  try {
    const projectId = templateProjectId(template.id);
    const files = await generateTemplateFiles(template, generation);
    if (!files || files.length === 0) {
      throw new Error(
        "Generation produced no files — try again or use a stronger model.",
      );
    }

    // Ensure the library project exists (fixed id, marked as template).
    if (!getProject(projectId)) {
      createProject(template.appName, template.brief, { id: projectId });
    }

    // Write the file set (replacing any stale content file-by-file).
    const keep = new Set(files.map((f) => f.path));
    for (const existing of listAppFiles(projectId)) {
      if (!keep.has(existing.path)) {
        deleteAppFile(projectId, existing.path);
      }
    }
    for (const f of files) {
      saveAppFile(projectId, f.path, f.content);
    }

    setProjectTemplate(projectId, {
      id: template.id,
      briefHash: briefHash(template.brief),
      promptHash: systemPromptHash(),
      generatedAt: new Date().toISOString(),
    });

    return statusFor(template);
  } finally {
    generating.delete(template.id);
  }
}

/**
 * One deletion/neutralization pass over the html: remove <img src=…>,
 * <script src=…></script>, and <link href=…> tags whose target is relative
 * and not among the files the model actually emitted, and neutralize
 * <a href=…> tags pointing at pages that were never emitted (rewritten to
 * href="#" — the navbar keeps its items, nothing navigates to a 404).
 *
 * Anchors are judged STRICTER than assets on purpose: a root-relative
 * asset (/vendored.js) may resolve same-origin, but a root-relative link
 * (/pricing) would leave the demo entirely — a static multi-page site can
 * only navigate among its own emitted files.
 *
 * ONE alternation regex matches all four tag shapes (a chained set of
 * one-shot replaces would let an earlier deletion splice the text into a
 * NEW well-formed tag the later passes never see). The pass is a MANUAL
 * exec loop that builds the output from segments — inter-match text is
 * appended verbatim, and each match is appended whole, dropped, or
 * replaced by a synthesized constant. No String.replace sanitization:
 * output is assembled from slices, so no pass ever grows the string and
 * the matcher never sees text it produced.
 */
const BROKEN_TAG_RE =
  /[ \t]*(?:<img\b[^>]*\bsrc=["']([^"'#]+)["'][^>]*>|<script\b[^>]*\bsrc=["']([^"'#]+)["'][^>]*>\s*<\/script>|<link\b[^>]*\bhref=["']([^"'#]+)["'][^>]*>|<a\b[^>]*\bhref=["']([^"'#]+)["'][^>]*>)[ \t]*\n?/gi;

/** The replacement for a dead anchor: a synthesized minimal open tag. */
const NEUTRAL_ANCHOR = '<a href="#">';

function stripBrokenPass(html: string, emitted: Set<string>): string {
  // Assets: root-relative targets may resolve same-origin, so they keep.
  const keepAsset = (target: string): boolean =>
    /^(https?:|data:|mailto:|tel:|#|\/)/.test(target) || emitted.has(target);
  // Anchors are stricter: no root-relative — a static demo cannot leave
  // itself, so /pricing would 404 exactly like a missing file.
  const keepAnchor = (target: string): boolean =>
    /^(https?:|data:|mailto:|tel:|#)/.test(target);

  let out = "";
  let last = 0;
  BROKEN_TAG_RE.lastIndex = 0;
  for (
    let m = BROKEN_TAG_RE.exec(html);
    m !== null;
    m = BROKEN_TAG_RE.exec(html)
  ) {
    out += html.slice(last, m.index);
    last = m.index + m[0].length;
    const [tag, imgSrc, scriptSrc, linkHref, anchorHref] = m;
    if (anchorHref !== undefined) {
      if (keepAnchor(anchorHref)) {
        out += tag;
        continue;
      }
      // Compare the path part only — fragments and query strings ride
      // along on an emitted page (post.html#intro, post.html?id=2).
      const filePath = anchorHref.split("#")[0].split("?")[0].trim();
      if (filePath && emitted.has(filePath)) {
        out += tag;
        continue;
      }
      // Dead anchor: the synthesized minimal open tag. The link's label
      // text and closing </a> live outside this match and survive; the
      // dead link loses its styling attributes, which is fine — it is
      // dead.
      out += NEUTRAL_ANCHOR;
      continue;
    }
    const target = imgSrc ?? scriptSrc ?? linkHref;
    if (keepAsset(target)) out += tag;
  }
  out += html.slice(last);
  return out;
}

/**
 * Relink placeholder nav anchors onto the pages the demo actually emitted.
 *
 * A multi-page demo whose entire navbar is `href="#"` renders fine and
 * links to nothing: the audit that checks "does every href resolve to an
 * emitted file" reports zero dead links, because "#" is a legal target.
 * The site still cannot be navigated, which is the whole point of a
 * multi-page demo.
 *
 * Models write those placeholders when a brief implies a nav but does not
 * spell out the filenames. The label usually names the page, so match it
 * against the emitted pages: "Pricing" -> pricing.html, "Home" ->
 * index.html. Matching is exact on a slug, so a legitimate in-page anchor
 * ("skip to content", "top") never matches anything and is left alone.
 */
const PLACEHOLDER_ANCHOR_RE = /<a\b([^>]*)\bhref="#"/gi;

function linkPageSlug(label: string): string {
  return label
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .replace(/\s+/g, "-");
}

function relinkPlaceholderNav(html: string, emitted: Set<string>): string {
  const pages = [...emitted].filter((p) => p.endsWith(".html"));
  // A label maps to a page only when the slug is unambiguous: two pages
  // slugging to the same word (about.html, about-me.html) means guessing.
  const byslug = new Map<string, string>();
  const ambiguous = new Set<string>();
  for (const page of pages) {
    const stem = linkPageSlug(page.replace(/\.html$/, ""));
    if (byslug.has(stem)) ambiguous.add(stem);
    byslug.set(stem, page);
  }

  let out = "";
  let last = 0;
  PLACEHOLDER_ANCHOR_RE.lastIndex = 0;
  for (
    let m = PLACEHOLDER_ANCHOR_RE.exec(html);
    m !== null;
    m = PLACEHOLDER_ANCHOR_RE.exec(html)
  ) {
    const openTag = m[0];
    const labelEnd = html.indexOf("</a>", m.index + openTag.length);
    if (labelEnd === -1) continue;
    const label = html.slice(m.index + openTag.length, labelEnd).replace(/<[^>]*>/g, "").trim();
    const slug = linkPageSlug(label);
    const target =
      slug === "" ? undefined : slug === "home" ? byslug.get("index") : byslug.get(slug);
    if (target === undefined || ambiguous.has(slug)) continue;

    // Slice the href out by hand (a String.replace on the tag reads as a
    // sanitising sink to CodeQL) and keep the anchor's other attributes.
    const hrefAt = openTag.toLowerCase().indexOf('href="#"');
    if (hrefAt === -1) continue;
    out += html.slice(last, m.index);
    out +=
      openTag.slice(0, hrefAt) +
      `href="${target}"` +
      openTag.slice(hrefAt + 'href="#"'.length);
    last = m.index + openTag.length;
  }
  out += html.slice(last);
  return out;
}

/**
 * Undo JSON-style backslash escaping inside html attributes.
 *
 * Models write data-URI favicons as `href="data:image/svg+xml,<svg
 * xmlns=\"http://www.w3.org/2000/svg\" …>"`. HTML has no backslash escape,
 * so the parser ends the attribute at the first `\"` and the remainder —
 * including a stray `">` — spills into the page as visible text above the
 * fold. Rewriting the escaped quote to a single quote keeps the attribute
 * intact AND leaves the embedded markup valid, because a double-quoted
 * attribute may legally contain single quotes.
 *
 * Manual exec loop over tags (no String.replace sink, no growth, so the
 * fixed-point loop in sanitizeDemoFiles still terminates).
 */
const TAG_RE = /<[a-zA-Z][^>]*>/g;

function unescapeAttrQuotes(html: string): string {
  let out = "";
  let last = 0;
  TAG_RE.lastIndex = 0;
  for (
    let m = TAG_RE.exec(html);
    m !== null;
    m = TAG_RE.exec(html)
  ) {
    if (!m[0].includes('\\"')) continue;
    out += html.slice(last, m.index);
    // Same length, character for character — only \" becomes '.
    out += m[0].split('\\"').join("'");
    last = m.index + m[0].length;
  }
  out += html.slice(last);
  return out;
}

/**
 * Remove tags that reference files the model never emitted — broken <img>,
 * dead <script src>/<link href> — and neutralize anchors pointing at pages
 * that were never emitted (rewritten to href="#"). Small models do this
 * constantly; the demo must look complete with only its own files.
 * Deterministic, so it works regardless of model quality. Returns the
 * cleaned file set.
 *
 * Two further repairs run alongside, both deterministic:
 *  - unescapeAttrQuotes, so JSON-escaped data URIs stop leaking text
 *  - relinkPlaceholderNav, so a multi-page demo's navbar actually goes
 *    somewhere. It runs AFTER the fixed-point loop on purpose: a dead
 *    anchor that neutralization just rewrote to "#" must stay dead, and
 *    relinking only fires when the label slugs to a page that really was
 *    emitted.
 *
 * The pass is iterated TO A FIXED POINT: a removal can splice the surrounding
 * text into a NEW well-formed tag (e.g. `<im` + `<link …>` + `g src=…>`), and
 * a single chained pass would leave that new broken tag behind. Each pass
 * only deletes or rewrites in place (never grows), so the loop terminates.
 */
export function sanitizeDemoFiles(files: ProjectFile[]): ProjectFile[] {
  const emitted = new Set(files.map((f) => f.path));
  return files.map((f) => {
    if (!f.path.endsWith(".html")) return f;
    let prev = f.content;
    let next = stripBrokenPass(prev, emitted);
    while (next !== prev) {
      prev = next;
      next = stripBrokenPass(prev, emitted);
    }
    next = relinkPlaceholderNav(unescapeAttrQuotes(next), emitted);
    return { ...f, content: next };
  });
}

/**
 * Non-streaming generation with the same degenerate-output retry as the chat
 * route: one automatic retry when the model returns an unclosed fence or
 * empty output.
 */
async function generateTemplateFiles(
  template: TemplateDef,
  generation: Awaited<ReturnType<typeof resolveGenerationFor>>,
): Promise<ProjectFile[] | null> {
  const prompt = `${template.brief}${TEMPLATE_SUFFIX}`;
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const result = streamText({
        model: generation.resolved.model,
        instructions: BUILDER_SYSTEM_PROMPT,
        prompt,
      });
      let text = "";
      for await (const delta of result.textStream) {
        text += delta;
      }
      const files = extractFiles(text);
      if (files && files.length > 0 && demoLooksComplete(files)) {
        return sanitizeDemoFiles(files);
      }
      console.log(
        `[templates] ${template.id}: degenerate attempt ${attempt + 1}`,
      );
    } catch (err) {
      console.error(`[templates] ${template.id}: generation error`, err);
    }
  }
  return null;
}

let warmStarted = false;

/**
 * Run a generation pass over `due` templates sequentially (gentle on rate
 * limits). Shared by the startup warmup and regenerate-all; progress is
 * exposed through the warming/warmingPending status fields so the gallery
 * can poll either kind of pass.
 */
async function runPass(due: TemplateDef[], startLabel: string): Promise<void> {
  console.log(
    `[templates] ${startLabel}: ${due.map((t) => t.id).join(", ")}`,
  );
  warmActive = true;
  for (const t of due) {
    warmPending.add(t.id);
  }

  for (const t of due) {
    const started = Date.now();
    const status = await generateTemplateDemo(t);
    warmPending.delete(t.id);
    if (status) {
      console.log(
        `[templates] ${t.id}: demo cached in ${((Date.now() - started) / 1000).toFixed(1)}s`,
      );
    } else {
      console.warn(
        `[templates] ${t.id}: pass generation failed — use the gallery button to retry`,
      );
    }
  }

  warmActive = false;
  console.log("[templates] pass finished");
}

/**
 * Warm the template cache once per server process: generate every template
 * that has no fresh demo yet (missing, stale brief, or stale system-prompt
 * hash), sequentially, in the background. Safe to call from
 * instrumentation.register(); failures are logged, never thrown, and any
 * template that failed stays available via the gallery's manual buttons.
 */
export async function warmTemplateCache(): Promise<void> {
  if (warmStarted) return;
  warmStarted = true;

  if (!(await isProviderConfigured())) {
    console.log(
      "[templates] warmup skipped — no AI provider configured (gallery has manual buttons)",
    );
    return;
  }

  const due = TEMPLATES.filter((t) => !statusFor(t).ready);
  if (due.length === 0) {
    console.log("[templates] warmup skipped — all demos already cached");
    return;
  }

  await runPass(due, "warming cache in background");
}

/**
 * Force-regenerate every template demo (user-triggered "Regenerate all").
 * Refused while another pass is running; otherwise returns immediately and
 * the pass progresses in the background — poll getTemplateCacheStatus().
 */
export async function startRegenerateAll(): Promise<{
  ok: boolean;
  error?: string;
}> {
  if (warmActive) {
    return { ok: false, error: "A generation pass is already running" };
  }
  // Claim the pass synchronously so two rapid requests can't both slip
  // through the async provider check below (warmActive is only otherwise
  // set inside runPass, after awaits).
  warmActive = true;
  if (!(await isProviderConfigured())) {
    warmActive = false;
    return {
      ok: false,
      error: "No AI provider configured — set one in Settings first.",
    };
  }
  // runPass re-marks the pending set; warmActive stays true throughout.
  void runPass([...TEMPLATES], "regenerating all template demos");
  return { ok: true };
}
