import { createHash } from "node:crypto";
import { streamText } from "ai";
import { BUILDER_SYSTEM_PROMPT, extractFiles } from "@/lib/prompt";
import { resolveGenerationFor } from "@/lib/providers/gateway";
import {
  createProject,
  deleteAppFile,
  getProject,
  listAppFiles,
  saveAppFile,
  setProjectTemplate,
} from "@/lib/store";
import {
  TEMPLATES,
  briefHash,
  templateProjectId,
  type TemplateDef,
} from "@/lib/templates";
import type { ProjectFile } from "@/lib/types";

/**
 * Template demo generation, shared by:
 *  - POST /api/templates   (on-demand from the gallery)
 *  - warmTemplateCache()   (background pass on server start, instrumentation)
 *
 * Demos live in fixed-id "library projects" (`tpl-<id>`) and are cached:
 * a demo is fresh only while its briefHash matches the current brief.
 */

/**
 * Extra instruction for template generation. The brief is the file plan:
 * a demo must emit exactly the files its brief describes — a multi-page
 * brief (SaaS site, blog) gets every page as a real .html file, never a
 * single-page stub whose nav links 404. Size guidance is per-file so a
 * five-file demo isn't squeezed into one 300-line page.
 */
const TEMPLATE_SUFFIX = `

This is a TEMPLATE DEMO: emit EXACTLY the files the brief describes — no more,
no fewer. When the brief names multiple pages (index.html, pricing.html,
about.html, …), every page is its own file linked with plain relative paths,
and the shared navbar/footer are duplicated per page (no build step). When it
describes a shared data file (e.g. posts.js), emit it and have the pages read
it. NEVER link to a file you did not emit. Keep each file focused and polished
(roughly 100–200 lines per page): a striking above-the-fold visual and a clean
section flow beat raw length.
IMPORTANT: never reference image files (img src, background url) — no local
assets and no external URLs. Draw all visuals with inline SVG or CSS shapes
and gradients only; the demo must look complete with just its own files.`;

/**
 * Cache key component: hash of everything the demo generation depends on
 * besides the brief. When the system prompt (or the template suffix) changes,
 * every cached demo becomes stale and is regenerated by the next warm pass.
 */
export function systemPromptHash(): string {
  return createHash("sha256")
    .update(BUILDER_SYSTEM_PROMPT, "utf8")
    .update(TEMPLATE_SUFFIX, "utf8")
    .digest("hex")
    .slice(0, 16);
}

export interface TemplateStatus {
  id: string;
  name: string;
  tagline: string;
  gradient: string;
  ready: boolean;
  generating: boolean;
  stale: boolean;
  files: string[];
  generatedAt?: string;
}

/** In-process lock so a warm pass and gallery clicks never double-generate. */
const generating = new Set<string>();

function statusFor(t: TemplateDef): TemplateStatus {
  const projectId = templateProjectId(t.id);
  const project = getProject(projectId);
  const files = project ? listAppFiles(projectId) : [];
  const fresh =
    project?.template?.briefHash === briefHash(t.brief) &&
    project?.template?.promptHash === systemPromptHash() &&
    files.length > 0;
  return {
    id: t.id,
    name: t.name,
    tagline: t.tagline,
    gradient: t.gradient,
    ready: fresh,
    generating: generating.has(t.id),
    stale: Boolean(project) && !fresh,
    files: files.map((f) => f.path),
    generatedAt: project?.template?.generatedAt,
  };
}

export interface TemplateCacheStatus {
  templates: TemplateStatus[];
  configured: boolean;
  /** True while the startup warm pass is still working through templates. */
  warming: boolean;
  /** Template ids still pending in the startup warm pass. */
  warmingPending: string[];
}

/** Warm-pass state, readable by the API for gallery polling. */
let warmActive = false;
const warmPending = new Set<string>();

export async function getTemplateCacheStatus(): Promise<TemplateCacheStatus> {
  return {
    templates: TEMPLATES.map(statusFor),
    configured: await isProviderConfigured(),
    warming: warmActive,
    warmingPending: [...warmPending],
  };
}

export async function isProviderConfigured(): Promise<boolean> {
  try {
    await resolveGenerationFor();
    return true;
  } catch {
    return false;
  }
}

/**
 * Generate (or regenerate when stale) one template's demo app server-side
 * into its library project. Returns the fresh status, or null when nothing
 * was generated (already generating / no provider / generation failed).
 * Never throws — the background warm pass and the fire-and-forget API path
 * both just want success/failure.
 */
export async function generateTemplateDemo(
  template: TemplateDef,
): Promise<TemplateStatus | null> {
  try {
    return await generateTemplateDemoOrThrow(template);
  } catch (err) {
    console.error(
      `[templates] ${template.id}: generation failed —`,
      err instanceof Error ? err.message : err,
    );
    return null;
  }
}

/**
 * Generate one template's demo, throwing on failure with a message suitable
 * for the gallery's error banner (no provider, degenerate output, …).
 */
export async function generateTemplateDemoOrThrow(
  template: TemplateDef,
): Promise<TemplateStatus> {
  if (generating.has(template.id)) {
    throw new Error("Already generating");
  }
  let generation;
  try {
    generation = await resolveGenerationFor();
  } catch (err) {
    throw new Error(
      err instanceof Error
        ? err.message
        : "No AI provider configured — set one in Settings first.",
    );
  }

  generating.add(template.id);
  try {
    const projectId = templateProjectId(template.id);
    const files = await generateTemplateFiles(template, generation);
    if (!files || files.length === 0) {
      throw new Error(
        "Generation produced no files — try again or use a stronger model.",
      );
    }

    // Ensure the library project exists (fixed id, marked as template).
    if (!getProject(projectId)) {
      createProject(template.appName, template.brief, { id: projectId });
    }

    // Write the file set (replacing any stale content file-by-file).
    const keep = new Set(files.map((f) => f.path));
    for (const existing of listAppFiles(projectId)) {
      if (!keep.has(existing.path)) {
        deleteAppFile(projectId, existing.path);
      }
    }
    for (const f of files) {
      saveAppFile(projectId, f.path, f.content);
    }

    setProjectTemplate(projectId, {
      id: template.id,
      briefHash: briefHash(template.brief),
      promptHash: systemPromptHash(),
      generatedAt: new Date().toISOString(),
    });

    return statusFor(template);
  } finally {
    generating.delete(template.id);
  }
}

/**
 * One deletion/neutralization pass over the html: remove <img src=…>,
 * <script src=…></script>, and <link href=…> tags whose target is relative
 * and not among the files the model actually emitted, and neutralize
 * <a href=…> tags pointing at pages that were never emitted (rewritten to
 * href="#" — the navbar keeps its items, nothing navigates to a 404).
 *
 * Anchors are judged STRICTER than assets on purpose: a root-relative
 * asset (/vendored.js) may resolve same-origin, but a root-relative link
 * (/pricing) would leave the demo entirely — a static multi-page site can
 * only navigate among its own emitted files.
 *
 * ONE alternation replace handles all four tag shapes (a chained set of
 * one-shot replaces would let an earlier deletion splice the text into a
 * NEW well-formed tag the later passes never see), and replacements are
 * always "", the original match, or a same-length-or-shorter rewrite, so a
 * pass never grows the string.
 */
const BROKEN_TAG_RE =
  /[ \t]*(?:<img\b[^>]*\bsrc=["']([^"'#]+)["'][^>]*>|<script\b[^>]*\bsrc=["']([^"'#]+)["'][^>]*>\s*<\/script>|<link\b[^>]*\bhref=["']([^"'#]+)["'][^>]*>|<a\b[^>]*\bhref=["']([^"'#]+)["'][^>]*>)[ \t]*\n?/gi;

function stripBrokenPass(html: string, emitted: Set<string>): string {
  // Assets: root-relative targets may resolve same-origin, so they keep.
  const keepAsset = (target: string): boolean =>
    /^(https?:|data:|mailto:|tel:|#|\/)/.test(target) || emitted.has(target);
  // Anchors are stricter: no root-relative — a static demo cannot leave
  // itself, so /pricing would 404 exactly like a missing file.
  const keepAnchor = (target: string): boolean =>
    /^(https?:|data:|mailto:|tel:|#)/.test(target);
  return html.replace(
    BROKEN_TAG_RE,
    (tag, imgSrc: string, scriptSrc: string, linkHref: string, anchorHref: string) => {
      if (anchorHref !== undefined) {
        if (keepAnchor(anchorHref)) return tag;
        // Compare the path part only — fragments and query strings ride
        // along on an emitted page (post.html#intro, post.html?id=2).
        const filePath = anchorHref.split("#")[0].split("?")[0].trim();
        if (filePath && emitted.has(filePath)) return tag;
        // Dead anchor: neutralize instead of delete.
        return tag.replace(/(\bhref=)["'][^"']*["']/i, '$1"#"');
      }
      const target = imgSrc ?? scriptSrc ?? linkHref;
      return keepAsset(target) ? tag : "";
    },
  );
}

/**
 * Remove tags that reference files the model never emitted — broken <img>,
 * dead <script src>/<link href> — and neutralize anchors pointing at pages
 * that were never emitted (rewritten to href="#"). Small models do this
 * constantly; the demo must look complete with only its own files.
 * Deterministic, so it works regardless of model quality. Returns the
 * cleaned file set.
 *
 * The pass is iterated TO A FIXED POINT: a removal can splice the surrounding
 * text into a NEW well-formed tag (e.g. `<im` + `<link …>` + `g src=…>`), and
 * a single chained pass would leave that new broken tag behind. Each pass
 * only deletes or rewrites in place (never grows), so the loop terminates.
 */
export function sanitizeDemoFiles(files: ProjectFile[]): ProjectFile[] {
  const emitted = new Set(files.map((f) => f.path));
  return files.map((f) => {
    if (!f.path.endsWith(".html")) return f;
    let prev = f.content;
    let next = stripBrokenPass(prev, emitted);
    while (next !== prev) {
      prev = next;
      next = stripBrokenPass(prev, emitted);
    }
    return { ...f, content: next };
  });
}

/**
 * Non-streaming generation with the same degenerate-output retry as the chat
 * route: one automatic retry when the model returns an unclosed fence or
 * empty output.
 */
async function generateTemplateFiles(
  template: TemplateDef,
  generation: Awaited<ReturnType<typeof resolveGenerationFor>>,
): Promise<ProjectFile[] | null> {
  const prompt = `${template.brief}${TEMPLATE_SUFFIX}`;
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const result = streamText({
        model: generation.resolved.model,
        instructions: BUILDER_SYSTEM_PROMPT,
        prompt,
      });
      let text = "";
      for await (const delta of result.textStream) {
        text += delta;
      }
      const files = extractFiles(text);
      if (files && files.length > 0) return sanitizeDemoFiles(files);
      console.log(
        `[templates] ${template.id}: degenerate attempt ${attempt + 1}`,
      );
    } catch (err) {
      console.error(`[templates] ${template.id}: generation error`, err);
    }
  }
  return null;
}

let warmStarted = false;

/**
 * Run a generation pass over `due` templates sequentially (gentle on rate
 * limits). Shared by the startup warmup and regenerate-all; progress is
 * exposed through the warming/warmingPending status fields so the gallery
 * can poll either kind of pass.
 */
async function runPass(due: TemplateDef[], startLabel: string): Promise<void> {
  console.log(
    `[templates] ${startLabel}: ${due.map((t) => t.id).join(", ")}`,
  );
  warmActive = true;
  for (const t of due) {
    warmPending.add(t.id);
  }

  for (const t of due) {
    const started = Date.now();
    const status = await generateTemplateDemo(t);
    warmPending.delete(t.id);
    if (status) {
      console.log(
        `[templates] ${t.id}: demo cached in ${((Date.now() - started) / 1000).toFixed(1)}s`,
      );
    } else {
      console.warn(
        `[templates] ${t.id}: pass generation failed — use the gallery button to retry`,
      );
    }
  }

  warmActive = false;
  console.log("[templates] pass finished");
}

/**
 * Warm the template cache once per server process: generate every template
 * that has no fresh demo yet (missing, stale brief, or stale system-prompt
 * hash), sequentially, in the background. Safe to call from
 * instrumentation.register(); failures are logged, never thrown, and any
 * template that failed stays available via the gallery's manual buttons.
 */
export async function warmTemplateCache(): Promise<void> {
  if (warmStarted) return;
  warmStarted = true;

  if (!(await isProviderConfigured())) {
    console.log(
      "[templates] warmup skipped — no AI provider configured (gallery has manual buttons)",
    );
    return;
  }

  const due = TEMPLATES.filter((t) => !statusFor(t).ready);
  if (due.length === 0) {
    console.log("[templates] warmup skipped — all demos already cached");
    return;
  }

  await runPass(due, "warming cache in background");
}

/**
 * Force-regenerate every template demo (user-triggered "Regenerate all").
 * Refused while another pass is running; otherwise returns immediately and
 * the pass progresses in the background — poll getTemplateCacheStatus().
 */
export async function startRegenerateAll(): Promise<{
  ok: boolean;
  error?: string;
}> {
  if (warmActive) {
    return { ok: false, error: "A generation pass is already running" };
  }
  // Claim the pass synchronously so two rapid requests can't both slip
  // through the async provider check below (warmActive is only otherwise
  // set inside runPass, after awaits).
  warmActive = true;
  if (!(await isProviderConfigured())) {
    warmActive = false;
    return {
      ok: false,
      error: "No AI provider configured — set one in Settings first.",
    };
  }
  // runPass re-marks the pending set; warmActive stays true throughout.
  void runPass([...TEMPLATES], "regenerating all template demos");
  return { ok: true };
}
