import type { ProviderConfig } from "../types";

/**
 * Catalog of supported providers. Anything with kind "openai-compatible"
 * works through the generic adapter, which covers effectively every
 * hosted or local inference API. Add new entries here (or via the
 * Custom provider in settings) to support new vendors — no code changes.
 */
export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  {
    id: "openai",
    name: "OpenAI",
    kind: "openai",
    baseURL: "https://api.openai.com/v1",
    defaultModel: "gpt-4.1",
    configured: false,
    note: "GPT-4.1 / GPT-5 family. Strong all-round app generation.",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    kind: "openai-compatible",
    baseURL: "https://api.anthropic.com/v1",
    defaultModel: "claude-sonnet-4-5",
    configured: false,
    note: "Claude models. Excellent front-end code quality.",
  },
  {
    id: "google",
    name: "Google AI Studio",
    kind: "openai-compatible",
    baseURL: "https://generativelanguage.googleapis.com/v1beta/openai",
    defaultModel: "gemini-2.5-pro",
    configured: false,
    note: "Gemini models via the OpenAI-compatible endpoint.",
  },
  {
    id: "groq",
    name: "Groq",
    kind: "openai-compatible",
    baseURL: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    configured: false,
    note: "Ultra-fast open models (Llama, Qwen, Kimi).",
  },
  {
    id: "mistral",
    name: "Mistral",
    kind: "openai-compatible",
    baseURL: "https://api.mistral.ai/v1",
    defaultModel: "mistral-large-latest",
    configured: false,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    kind: "openai-compatible",
    baseURL: "https://api.deepseek.com/v1",
    defaultModel: "deepseek-chat",
    configured: false,
    note: "DeepSeek V3 / R1. Great price/performance for code.",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    kind: "openai-compatible",
    baseURL: "https://openrouter.ai/api/v1",
    defaultModel: "anthropic/claude-sonnet-4.5",
    configured: false,
    note: "Access 300+ models from every vendor with one key.",
  },
  {
    id: "together",
    name: "Together AI",
    kind: "openai-compatible",
    baseURL: "https://api.together.xyz/v1",
    defaultModel: "Qwen/Qwen2.5-Coder-32B-Instruct",
    configured: false,
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    kind: "openai-compatible",
    baseURL: "https://api.fireworks.ai/inference/v1",
    defaultModel: "accounts/fireworks/models/kimi-k2-instruct",
    configured: false,
  },
  {
    id: "xai",
    name: "xAI",
    kind: "openai-compatible",
    baseURL: "https://api.x.ai/v1",
    defaultModel: "grok-4",
    configured: false,
  },
  {
    id: "cloudflare-ai",
    name: "Cloudflare Workers AI (free)",
    kind: "openai-compatible",
    baseURL: "https://api.cloudflare.com/client/v4/accounts/{account}/ai/v1",
    defaultModel: "@cf/meta/llama-3.1-8b-instruct-fast",
    configured: false,
    note: "Free-tier serverless inference — no card needed. Reuses your Cloudflare deploy credentials automatically (connect Deploy in the publish panel, or paste a token here).",
  },
  {
    id: "ollama",
    name: "Ollama (local)",
    kind: "openai-compatible",
    baseURL: "http://localhost:11434/v1",
    defaultModel: "qwen2.5-coder:7b",
    configured: false,
    note: "Runs fully local — no API key needed if Ollama is running.",
  },
  {
    id: "lmstudio",
    name: "LM Studio (local)",
    kind: "openai-compatible",
    baseURL: "http://localhost:1234/v1",
    defaultModel: "qwen2.5-coder-7b-instruct",
    configured: false,
    note: "Start the LM Studio local server, no API key needed.",
  },
  {
    id: "vllm",
    name: "vLLM / self-hosted",
    kind: "openai-compatible",
    baseURL: "http://localhost:8000/v1",
    defaultModel: "meta-llama/Llama-3.1-8B-Instruct",
    configured: false,
    note: "Any vLLM, TGI, llama.cpp or text-generation-webui server.",
  },
  {
    id: "custom",
    name: "Custom OpenAI-compatible",
    kind: "openai-compatible",
    baseURL: "",
    defaultModel: "",
    configured: false,
    note: "Any endpoint that speaks the OpenAI chat completions API.",
  },
];
