import type { ProviderConfig } from "../types";

/**
 * Catalog of supported providers. Anything with kind "openai-compatible"
 * works through the generic adapter, which covers effectively every
 * hosted or local inference API. Add new entries here (or via the
 * Custom provider in settings) to support new vendors — no code changes.
 *
 * Every hosted entry below is verified, not remembered: the base URL
 * answers an unauthenticated POST to `/chat/completions` (401/403 = the
 * route exists) and `defaultModel` comes from the vendor's own docs or a
 * live `/models` response. Do not add an endpoint you have not probed —
 * a plausible-looking URL is the one defect this catalog cannot catch.
 * Entries carrying a placeholder host (Azure) or a region (Bedrock) must
 * say so in `note`; the user edits the base URL in Settings.
 */
export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  {
    id: "openai",
    name: "OpenAI",
    kind: "openai",
    baseURL: "https://api.openai.com/v1",
    defaultModel: "gpt-4.1",
    configured: false,
    note: "GPT-4.1 / GPT-5 family. Strong all-round app generation.",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    kind: "openai-compatible",
    baseURL: "https://api.anthropic.com/v1",
    defaultModel: "claude-sonnet-4-5",
    configured: false,
    note: "Claude models. Excellent front-end code quality.",
  },
  {
    id: "google",
    name: "Google AI Studio",
    kind: "openai-compatible",
    baseURL: "https://generativelanguage.googleapis.com/v1beta/openai",
    defaultModel: "gemini-2.5-pro",
    configured: false,
    note: "Gemini models via the OpenAI-compatible endpoint.",
  },
  {
    id: "groq",
    name: "Groq",
    kind: "openai-compatible",
    baseURL: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    configured: false,
    note: "Ultra-fast open models (Llama, Qwen, Kimi).",
  },
  {
    id: "mistral",
    name: "Mistral",
    kind: "openai-compatible",
    baseURL: "https://api.mistral.ai/v1",
    defaultModel: "mistral-large-latest",
    configured: false,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    kind: "openai-compatible",
    baseURL: "https://api.deepseek.com/v1",
    defaultModel: "deepseek-chat",
    configured: false,
    note: "DeepSeek V3 / R1. Great price/performance for code.",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    kind: "openai-compatible",
    baseURL: "https://openrouter.ai/api/v1",
    defaultModel: "anthropic/claude-sonnet-4.5",
    configured: false,
    note: "Access 300+ models from every vendor with one key.",
  },
  {
    id: "together",
    name: "Together AI",
    kind: "openai-compatible",
    baseURL: "https://api.together.xyz/v1",
    defaultModel: "Qwen/Qwen2.5-Coder-32B-Instruct",
    configured: false,
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    kind: "openai-compatible",
    baseURL: "https://api.fireworks.ai/inference/v1",
    defaultModel: "accounts/fireworks/models/kimi-k2-instruct",
    configured: false,
  },
  {
    id: "xai",
    name: "xAI",
    kind: "openai-compatible",
    baseURL: "https://api.x.ai/v1",
    defaultModel: "grok-4",
    configured: false,
  },
  {
    id: "azure",
    name: "Azure OpenAI",
    kind: "openai-compatible",
    baseURL: "https://YOUR-RESOURCE-NAME.openai.azure.com/openai/v1",
    defaultModel: "gpt-4.1",
    configured: false,
    note: "Azure's v1 API is plain OpenAI-compatible (no api-version). Replace YOUR-RESOURCE-NAME with your resource name in Settings, and set the default model to your deployment name.",
  },
  {
    id: "bedrock",
    name: "Amazon Bedrock",
    kind: "openai-compatible",
    baseURL: "https://bedrock-runtime.us-east-1.amazonaws.com/openai/v1",
    defaultModel: "openai.gpt-oss-120b-1:0",
    configured: false,
    note: "Swap us-east-1 for your AWS region. Needs a Bedrock API key (Bearer) — SigV4 keys are not supported here. This endpoint has no GET /models, so pick the model yourself.",
  },
  {
    id: "cohere",
    name: "Cohere",
    kind: "openai-compatible",
    baseURL: "https://api.cohere.ai/compatibility/v1",
    defaultModel: "command-a-plus-05-2026",
    configured: false,
    note: "Command models through Cohere's OpenAI compatibility layer.",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    kind: "openai-compatible",
    baseURL: "https://api.perplexity.ai",
    defaultModel: "sonar",
    configured: false,
    note: "Web-grounded answers. Sonar chat-completions moved to the Agent API in Sep 2026 — model ids and request shape are unchanged.",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    kind: "openai-compatible",
    baseURL: "https://api.cerebras.ai/v1",
    defaultModel: "llama-3.3-70b",
    configured: false,
    note: "Wafer-scale inference — the fastest tokens-per-second of any host.",
  },
  {
    id: "sambanova",
    name: "SambaNova",
    kind: "openai-compatible",
    baseURL: "https://api.sambanova.ai/v1",
    defaultModel: "DeepSeek-V3.1",
    configured: false,
    note: "Fast hosted open-weight models (DeepSeek, Llama, gpt-oss).",
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    kind: "openai-compatible",
    baseURL: "https://integrate.api.nvidia.com/v1",
    defaultModel: "deepseek-ai/deepseek-v4.1-flash",
    configured: false,
    note: "Hosted NIM endpoints from build.nvidia.com — free API keys available.",
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    kind: "openai-compatible",
    baseURL: "https://api.deepinfra.com/v1/openai",
    defaultModel: "deepseek-ai/DeepSeek-V4-Pro",
    configured: false,
    note: "Cheap, broad open-weight catalog. Note the /v1/openai path.",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    kind: "openai-compatible",
    baseURL: "https://api.siliconflow.com/v1",
    defaultModel: "Qwen/Qwen3-32B",
    configured: false,
    note: "Hosted Qwen / DeepSeek / Kimi. Mainland-China accounts: set the base URL to https://api.siliconflow.cn/v1",
  },
  {
    id: "qwen",
    name: "Alibaba Model Studio (Qwen)",
    kind: "openai-compatible",
    baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    defaultModel: "qwen3-max",
    configured: false,
    note: "Qwen models via the international DashScope endpoint. Mainland China: https://dashscope.aliyuncs.com/compatible-mode/v1",
  },
  {
    id: "moonshot",
    name: "Moonshot AI (Kimi)",
    kind: "openai-compatible",
    baseURL: "https://api.moonshot.ai/v1",
    defaultModel: "kimi-k3",
    configured: false,
    note: "Kimi models with a 1M-token context. China endpoint: https://api.moonshot.cn/v1",
  },
  {
    id: "zai",
    name: "Z.ai / Zhipu (GLM)",
    kind: "openai-compatible",
    baseURL: "https://api.z.ai/api/paas/v4",
    defaultModel: "glm-5.3",
    configured: false,
    note: "GLM family from Zhipu. Mainland-China platform: https://open.bigmodel.cn/api/paas/v4",
  },
  {
    id: "minimax",
    name: "MiniMax",
    kind: "openai-compatible",
    baseURL: "https://api.minimax.io/v1",
    defaultModel: "MiniMax-M3",
    configured: false,
    note: "M-series models, strong on long-context and agent workloads.",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    kind: "openai-compatible",
    baseURL: "https://router.huggingface.co/v1",
    defaultModel: "deepseek-ai/DeepSeek-V4-Pro",
    configured: false,
    note: "Inference Providers router — hundreds of open models, routed across hosts, on one key.",
  },
  {
    id: "novita",
    name: "Novita AI",
    kind: "openai-compatible",
    baseURL: "https://api.novita.ai/v3/openai",
    defaultModel: "zai-org/glm-5.3-flash",
    configured: false,
    note: "Serverless open-weight inference. Note the /v3/openai path.",
  },
  {
    id: "nebius",
    name: "Nebius AI Studio",
    kind: "openai-compatible",
    baseURL: "https://api.studio.nebius.com/v1",
    defaultModel: "Qwen/Qwen3-235B-A22B",
    configured: false,
    note: "Nebius's OpenAI-compatible API for open models.",
  },
  {
    id: "upstage",
    name: "Upstage",
    kind: "openai-compatible",
    baseURL: "https://api.upstage.ai/v1",
    defaultModel: "solar-pro4",
    configured: false,
    note: "Solar models, tuned for document-heavy and agentic work.",
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    kind: "openai-compatible",
    baseURL: "https://api.ai21.com/studio/v1",
    defaultModel: "jamba-1.5-large",
    configured: false,
    note: "Jamba models. Their /models endpoint returns an empty list, so set the default model yourself.",
  },
  {
    id: "cloudflare-ai",
    name: "Cloudflare Workers AI (free)",
    kind: "openai-compatible",
    baseURL: "https://api.cloudflare.com/client/v4/accounts/{account}/ai/v1",
    defaultModel: "@cf/meta/llama-3.1-8b-instruct-fast",
    configured: false,
    note: "Free-tier serverless inference — no card needed. Reuses your Cloudflare deploy credentials automatically (connect Deploy in the publish panel, or paste a token here).",
  },
  {
    id: "ollama",
    name: "Ollama (local)",
    kind: "openai-compatible",
    baseURL: "http://localhost:11434/v1",
    defaultModel: "qwen2.5-coder:7b",
    configured: false,
    note: "Runs fully local — no API key needed if Ollama is running.",
  },
  {
    id: "lmstudio",
    name: "LM Studio (local)",
    kind: "openai-compatible",
    baseURL: "http://localhost:1234/v1",
    defaultModel: "qwen2.5-coder-7b-instruct",
    configured: false,
    note: "Start the LM Studio local server, no API key needed.",
  },
  {
    id: "vllm",
    name: "vLLM / self-hosted",
    kind: "openai-compatible",
    baseURL: "http://localhost:8000/v1",
    defaultModel: "meta-llama/Llama-3.1-8B-Instruct",
    configured: false,
    note: "Any vLLM, TGI, llama.cpp or text-generation-webui server.",
  },
  {
    id: "custom",
    name: "Custom OpenAI-compatible",
    kind: "openai-compatible",
    baseURL: "",
    defaultModel: "",
    configured: false,
    note: "Any endpoint that speaks the OpenAI chat completions API.",
  },
];
